name: Projeto S107

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:   
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn clean test
      
      - name: Test Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: target/surefire-reports/**/*.xml  

  build:       
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifact
          path: target/*.jar 

  send-email-test:
    needs: test
    runs-on: ubuntu-latest
    env:
      EMAIL: "arthur.f@gec.inatel.br"

    steps:
      - uses: actions/checkout@v4

      - name: Send email
        run: sh ./scripts/mail_test.sh ${EMAIL}

  send-email-build:
    needs: build
    runs-on: ubuntu-latest
    env:
      EMAIL: "arthur.f@gec.inatel.br"

    steps:
      - uses: actions/checkout@v4

      - name: Send email
        run: sh ./scripts/mail_build.sh ${EMAIL}
